name: Build DA-HP Arch ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: "--privileged"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Container
        run: |
          pacman -Sy --noconfirm
          echo "Container is working and has network access."
