name: Proxy Download PMOS

on:
  push:
    paths:
      - '.github/workflows/proxy-download.yml'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Upload
        run: |
          URL="https://images.postmarketos.org/pine64-pinephone/v25.12/console/postmarketOS-v25.12-pine64-pinephone-console.img.xz"
          echo "Downloading $URL..."
          curl -L -O "$URL"
          echo "Download complete."
          
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pmos-pinephone-console
          path: postmarketOS-v25.12-pine64-pinephone-console.img.xz
          retention-days: 1
