name: Proxy Download Fedora

on:
  push:
    paths:
      - '.github/workflows/proxy-download-fedora.yml'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Upload
        run: |
          # Correct stable Fedora 44 link
          URL="https://download.fedoraproject.org/pub/fedora/linux/releases/44/Spins/aarch64/images/Fedora-KDE-Mobile-Disk-44-1.7.aarch64.raw.xz"
          echo "Downloading $URL..."
          curl -f -L -O "$URL"
          echo "Download complete."
          ls -lh
          
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: fedora-pinephone-mobile
          path: Fedora-KDE-Mobile-Disk-44-1.7.aarch64.raw.xz
          retention-days: 1
